### ISSUE TITLE
シェイプ記述誤り: RevisionOfCourseOfStudyShapeにおける issuedPeriod プロパティのリンク先クラス指定はPeriodとすべき

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#10]
https://w3id.org/jp-cos/RevisionOfCourseOfStudyShape における ``cs:issuedPeriod`` プロパティはリソース先クラスとして https://
w3id.org/jp-cos/IssuedPeriod が指定されているが、実際には https://
w3id.org/jp-cos/Period となっているので、シェイプ記述を修正した方が良い。

実際のデータ例： https://w3id.org/jp-cos/Kindergarten/2017/2017

**Comment by yegusa** [comment]
プロパティは、 issudePeriod のままでいいかな？　とりあえず、そのままにしとくね。
（プロパティは issuedPeriod で、その先のクラスがPeriodってなる。ちょっと不均衡かな？）

Item、CourseOfStudy,CourseOfStudyRevision の
cs:issuedPeriod プロパティのリソース先クラスを 
https://w3id.org/jp-cos/Period に修正しました（IssuedPeriod をPeriodにした）

**Comment by masao** [comment]
修正を確認したのでクローズします。
