### ISSUE TITLE
NHK for School API v2対応

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#105]
現在利用しているAPI V1は2025年度中に停止される模様。

API V2は範囲も増えているようなので、そちらに乗り換える予定。

cf. https://school-api-portal.nhk.or.jp/info-20240226
cf. https://school-api-portal.nhk.or.jp/info

**Comment by masao** [comment]
API v2に移行しました。検索範囲が幼稚園や特別支援、高校まで広がったようなので、すべての指導要領細目ページで検索機能を出すようにしました。
※API v1時代は 小中の 社会と理科のみ。

**Comment by masao** [comment]
検索できるようになったコンテンツ例
* 高校： https://w3id.org/jp-cos/8413503221400000
* 特別支援： https://w3id.org/jp-cos/86O0400310000000
* 幼稚園： https://w3id.org/jp-cos/81l3003100000000

**Comment by yegusa** [comment]
すごい！確認しました。クローズします。
