### ISSUE TITLE
SPARQLエンドポイントの公開

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#108]
jp-textbook/jp-textbook.github.io#554 と同様のやり方で。

=> https://dydra.com/masao/jp-cos/sparql

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。
が、人間フレンドリーなURLのほうがいいかも？

https://dydra.com/masao/jp-textbook/@query

かな？

**Comment by masao** [comment]
6300c4715cf9e9eef6f86c1c9677a3d4c207ed11 URLを修正しました

**Comment by yegusa** [comment]
確認しました。クローズします。
