### ISSUE TITLE
リンク先誤り：教科「特別の教科　道徳」

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#11]
細目リソース https://w3id.org/jp-cos/83K0300200000000 における教科リソースへのリンク先が <https://w3id.org/jp-cos/LowerSecondary/2017/特別の教科　道徳> となっているが、リンク先教科は空白を除いた「特別の教科道徳」とすべき。

**Comment by yegusa** [comment]
直しました。

**Comment by masao** [comment]
まだ直っていないようです。

**Comment by yegusa** [comment]
あれ～。直した～。今度こそ。

**Comment by masao** [comment]
修正を確認したのでクローズします。
