### ISSUE TITLE
教科・科目「情報」の英訳など、最新の訳に対応していない。

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#114]
関連： https://github.com/jp-textbook/jp-textbook.github.io/issues/600

例：情報の訳など。
新しい教科「情報」と科目「情報 I/II」の訳語は Information Study から Informatics に変更になった。
[https://w3id.org/jp-cos/UpperSecondary/2018/情報](https://w3id.org/jp-cos/UpperSecondary/2018/%E6%83%85%E5%A0%B1)

平成30年改訂高等校学習指導要領英訳版（仮訳）
https://www.mext.go.jp/a_menu/shotou/new-cs/1417513.htm

こっちを使って英訳を作り直すべき。

新しくできた「科目」や「教科」があれば上記の英訳を使って作成していたけど、科目名や教科名が旧学習指導要領にあるものは新しい英訳からは英訳を作成していなかったのでこの現象が起きたようです。まさか、同じ教科や科目名で、英訳が変わっていることがあるとは思わなかったので。

**Comment by yegusa** [comment]
subject とsubjectArea のデータを作成しなおしました。
幼稚園、小学校、高等学校の科目と
全学校種の教科は精査しました。

科目は、中学校、特別支援学校のは精査しなおしができてませんが、また後日やろうかと思います。別issueにします。

**Comment by masao** [comment]
登録しました

**Comment by yegusa** [comment]
確認しました。

Infomatics になっているのを確認しました。

教科の例：
[https://w3id.org/jp-cos/UpperSecondary/2018/情報](https://w3id.org/jp-cos/UpperSecondary/2018/%E6%83%85%E5%A0%B1)

科目の例：
[https://w3id.org/jp-cos/UpperSecondary/2018/情報/情報I](https://w3id.org/jp-cos/UpperSecondary/2018/%E6%83%85%E5%A0%B1/%E6%83%85%E5%A0%B1I)
