### ISSUE TITLE
教科や科目の英語の出典をブランクノードでとなっている（英語の出典をブランクノードではなくした件）

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#120]
#115 に関連して、aboutの説明で、教科や科目の英語の出典をブランクノードで～のままとなっている。

学習指導要領LOD / LOD_shapes_20241220.xlsx の反映が必要かも？

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
確認しました。クローズします。
