### ISSUE TITLE
「総則」リソースの科目リンクの扱い

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#13]
https://w3id.org/jp-cos/UpperSecondary/2018/総則 などの「総則」を表現する教科は科目を持たないが、一方で教科シェイプにおいては ``cs:hasSubject``プロパティは必須プロパティとして指定しているので、例外として許容するか議論が必要と思われる。

**Comment by yegusa** [comment]
科目をもたない教科があっていい気がする～。ので、教科シェイプの定義を変えるのがいい気がする。

**Comment by yegusa** [comment]
これ、 #21 で解決することにするため、クローズする
