### ISSUE TITLE
クラス RevisionOfCourseOfStudy からCourseOfStudyRevisionに変更する

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#14]
- [x] #5 schema-class をクラス記述をRevisionOfCourseOfStudy からCourseOfStudyRevisionに変更に変更
- [x] cs-revision-*.ttl のクラス記述をRevisionOfCourseOfStudy からCourseOfStudyRevisionに変更
- [x] （注：schema-property-*.ttl は、既になっているので修正必要なし） 
- [x] LOD_shapes_*.xlsx の各リソースからの対象クラスをRevisionOfCourseOfStudy からCourseOfStudyRevisionに変更（いっぱいあるので検索して修正すること）

**Comment by yegusa** [comment]
修正しました

**Comment by masao** [comment]
一つだけ： 
学習指導要領シェイプ記述での dct:hasVersion において、以下の指定があるが、 CourseOfStudyRevis**i**on の最後の i が無いスペルミス・・・

```
  sh:property [
    sh:path <http://purl.org/dc/terms/hasVersion>;
    sh:name "別バージョン"@ja;
    sh:name "Other versions"@en;
    sh:description "複数の改正がある場合、改正の件数分、繰り返される。"@ja;
    sh:description "Repeatable. It corresponds to the course of study revision."@en;
    skos:example <https://w3id.org/jp-cos/Elementary/2017/2017>;
    sh:minCount 1;
    sh:class <https://w3id.org/jp-cos/CourseOfStudyRevison>;
    sh:order 7
  ];
```

**Comment by masao** [comment]
修正を確認したのでクローズします。
