### ISSUE TITLE
学習指導要領シェイプにhasSubjectプロパティの記述が無い

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#17]
https://jp-cos.github.io/LowerSecondary/2008/ などのように、hasSubject プロパティ（科目を持つプロパティ）があるにもかかわらず、シェイプ記述では説明が無い。

**Comment by yegusa** [comment]
シェイプに追加しておきました。

**Comment by masao** [comment]
追加を確認したのでクローズします。
