### ISSUE TITLE
学習指導要領リソースで issuedPeriod プロパティを持たないものがある

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#19]
シェイプ記述ではこのプロパティは必須だが https://w3id.org/jp-cos/LowerSecondary/1989 など、cs:issuedPeriod プロパティを持たないものがある。

**Comment by yegusa** [comment]
あー、わざと出ないようにしてたけど、考えてみたら、コードあったので、付けときますー。データ作成し直しておきました。

**Comment by masao** [comment]
修正を確認したのでクローズします。
