### ISSUE TITLE
英語表記出典リソースにおけるcs:curriculumプロパティをcs:courseOfStudyに変更

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#22]
基本的に同じような対応学習指導要領を示しているので、同じプロパティで良いかと。

**Comment by yegusa** [comment]
subject-*.ttl
subjectArea-*.ttl
schema-property-*.ttl
LOD_shapes_20211206.xlsx

に反映しました。

**Comment by masao** [comment]
https://w3id.org/jp-cos/LowerSecondary/2008/外国語/英語 修正を確認したのでクローズします。
