### ISSUE TITLE
細目における親子関係の再検討

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#24]
https://w3id.org/jp-cos/83K0000000000000 「第3章　特別の教科道徳」における親リソースが
* 「第2章 各教科」、
* そのさらに親リソースが「第1章 総則」

となるのは、さすがに違和感がある。それぞれを独立させて親子としないようにしたほうがよいかも。
要検討。

**Comment by yegusa** [comment]
こんな感じの階層関係にするのでどうでしょうか？

- 第１章　総則
- 第２章　各教科
   - 第１節　国語
   - 第２節　社会
   - 第３節　算数
   - 第４節　理科
   - 第５節　生活
   - 第６節　音楽
   - 第７節　図画工作
   - 第８節　家庭
   - 第９節　体育
   - 第10節　外国語
- 第３章　特別の教科　道徳
- 第４章　外国語活動
- 第５章　総合的な学習の時間
- 第６章　特別活動

**Comment by yegusa** [comment]
文書としてはこういう構造：

- 第１章　総則
   - 第２章　各教科
       - 第１節　国語
       - 第２節　社会
       - 第３節　算数
       - 第４節　理科
       - 第５節　生活
       - 第６節　音楽
       - 第７節　図画工作
       - 第８節　家庭
       - 第９節　体育
       - 第10節　外国語
       - 第３章　特別の教科　道徳
       - 第４章　外国語活動
       - 第５章　総合的な学習の時間
       - 第６章　特別活動

**Comment by yegusa** [comment]
(a)文書の構造と、(b)コードがあらわしているが構造ミスマッチだけれども、意味的には、(b)でいい感じがするので、(b)の方向（つまり、今までのとおりで変更なし）でいいかと思います！

**Comment by masao** [comment]
承知です。特に変更無しということにしてクローズします。
