### ISSUE TITLE
関係のある教科、関係のある科目にrdf:type, schema:nameを追加する

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#26]
https://w3id.org/jp-cos/ElementaryAndLowerSecondaryDeptSNES/2017/総則

小学部・中学部の総則として、上記URIがつかわれているが、タイトルなどの教科用プロパティが指定されていない状態なので、少し調整が必要と思われる。

**Comment by yegusa** [comment]
ああ、これ、障害ありのURIのリソースとつなげるためだけの親リソースなんです。
教科等リソースじゃなくて、 https://w3id.org/jp-cos/RelatedSubjectArea リソースなんです。

だから、タイトルとかも付けてないの。

総則以外にもあるやつよ。以下は、生物

https://w3id.org/jp-cos/ElementaryAndLowerSecondaryDeptSNES/2017/生活

こういうのいらないかなあ。

**Comment by yegusa** [comment]
まずは、以下が必要ってことかと思います。

- [ ] 関係のある教科等リソースに rdf:type, rdfs:label をつける
- [ ] 関係のある教科等リソースに↑のshape を反映
- [ ] 関係のある科目等リソースに rdf:type,rdfs:label をつける
- [ ] 関係のある科目等リソースに↑のshape を反映

**Comment by yegusa** [comment]
subjectArea-20211216.ttl
subect-20211216.ttl
LOD_shapes_20211216.xlsx

に反映しました。

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
https://w3id.org/jp-cos/ElementaryAndLowerSecondaryDeptSNES/2017/総則
https://w3id.org/jp-cos/ElementaryAndLowerSecondaryDeptSNES/2017/生活

確認しました。
よさそうに思いますので、クローズします。
