### ISSUE TITLE
ライセンス表示を追記する

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#27]
トップページと about ページの両方に入れておく必要がありそう

**Comment by masao** [comment]
ライセンス表示を追記しました。

**Comment by yegusa** [comment]
ライセンス表示としては良いと思います。

が、表示となっているのに、何を表示すべきかわからんような？　#33 に関係するかもですが、プロジェクト名か何かを書いとく必要あるよね？教科書LODだったら、「© 2017-2021 教科書LODプロジェクト」とかを一番下にかいているけど、そういうのがいるかも？

**Comment by yegusa** [comment]
ま、これはクローズして、著作者表示については別のissueとしてあげますね。クローズします。
