### ISSUE TITLE
ttl 内に、 "\" あるとだめなのかもしれない（ cs:school\/ElementaryDeptSNES など）

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#31]
URIを短縮表記するために、

```
  cs:school cs:school\/ElementaryDeptSNES,cs:school\/LowerSecondaryDeptSNES; #学校種別と障害分類 2桁目
```

ってしてたんだけど、

https://jpsearch.go.jp/rdf/sparql/easy/?describe=https%3A%2F%2Fw3id.org%2Fjp-cos%2F8220263211000000

ここで、 \ がでちゃってるのよねえ。

**Comment by masao** [comment]
その後、特に問題なくなったいるようなので、クローズします
