### ISSUE TITLE
about にリソースのモデル概要図を追加

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#35]
PowerPoint で作る？
学習指導要領のリソースのモデル概要がわかる図を載せる。

例：教科書LOD
![image](https://user-images.githubusercontent.com/1328499/146250534-b2dbf037-62ce-4aa6-a235-39f8135bc2a0.png)

**Comment by yegusa** [comment]
作ってみました
![lod-model](https://user-images.githubusercontent.com/1328499/146314096-9a65c515-1f49-4b8e-9297-f20d2ae5855a.png)
。

**Comment by yegusa** [comment]
障害分類と段階があるバージョンも作成
![lod-model2](https://user-images.githubusercontent.com/1328499/146322046-1d5f8af9-fb02-490e-b2a3-9e1fc42f4540.png)

**Comment by masao** [comment]
追加しました

**Comment by yegusa** [comment]
いいかんじです。クローズします。
