### ISSUE TITLE
著作者の表示

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#38]
ライセンスが CC BY となっているのに、何を表示すべきかわからんような？　#33 に関係するかもですが、プロジェクト名か何かを書いとく必要あるよね？教科書LODだったら、「© 2017-2021 教科書LODプロジェクト」とかを一番下にかいているけど、そういうのがいりますね。

© 2021 教育データプラス研究会

とかでしょうか。

**Comment by masao** [comment]
> © 2021 教育データプラス研究会

フッタ―に追記しました。

**Comment by yegusa** [comment]
よいとおもいます！クローズします。
