### ISSUE TITLE
about Sourceofenglishname となっている。

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#39]
- NG: Sourceofenglishname
- OK: 英語表記の出典

![学習指導要領LODについて](https://user-images.githubusercontent.com/1328499/146634338-9b5ecbea-cac3-4796-a620-9773a6cc236c.png)

このようになっています。

schema-class-*.ttl

がまちがえてるからかも！

https://w3id.org/jp-cos/SourceOfEnglishNameShape ってなってた！（あれ、どっかで直したきがしたんだけどな）
https://w3id.org/jp-cos/SourceOfEnglishName に直す必要がありますね。

**Comment by yegusa** [comment]
schema-class-20211218.ttl として作っておきました。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
