### ISSUE TITLE
テーマカラーとロゴを決める

### ISSUE THREAD

**Issue by ta-niiyan** [jp-cos/jp-cos.github.io#4]
教科書LODのテーマカラーが紺色？ネイビーなので、暖色系で検討してみる。

**Comment by ta-niiyan** [comment]
![jp-cosLOD_logo](https://user-images.githubusercontent.com/3224047/145918871-b537cde9-90a3-4498-b492-d2808dfcdd5e.png)

**Comment by ta-niiyan** [comment]
ロゴとキーカラーはこのような感じはいかがでしょうか。
＜ロゴ＞
教科書などの基本／源ということで、見本帳をイメージしてみました。教科書LODの「本」とも親和性高いかも？

＜カラー＞
・キーカラー（背景色）：クロームイエロー RGB(253, 208, 0)　ゴッホがよく使っていた黄色と言われています。
・アクセントカラー（線画）：ネイビーブルー RGB(15, 36, 77)　教科書LODで使用しているネイビーをピックアップしてみました

**Comment by yegusa** [comment]
すごくよいです！slackでいただいたファビコンとともに、サイトに反映したいですね。 @masao よろ～

**Comment by masao** [comment]
ロゴと背景色、favicon を追加してみました。

**Comment by yegusa** [comment]
めっちゃいいとおもいます！クローズします。
