### ISSUE TITLE
英語出典にリソースURIを付けたほうがよいかも　改めラベル付きブランクノードに

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#42]
https://w3id.org/jp-cos/UpperSecondary/2018 において、被参照元で、すべての教科・科目からの参照がついているので、末尾に大量にブランクノード分の英語出典参照が記載されている。これは単一の情報なので同一のURIリソースにあたる形で参照したほうがよい。重複した情報がかかれないようにしたほうがよさそう。
（優先度：低）

**Comment by yegusa** [comment]
どういうURIにしようかなと。案求む～

**Comment by masao** [comment]
ラベル付きのブランクノードで同じリソースであることを担保するほうが楽かも？

``_:UpperSecondary-2018-国語-english-name`` など?

**Comment by yegusa** [comment]
ラベル付きのブランクノードで考えてみます。

**Comment by yegusa** [comment]
ブランクノードでやりました。
修正しました。

cs-subjectArea-20211223.ttl
cs-subject-20211223.ttl

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
英語の出典が2つでちゃうのかあ。まあ、しゃーないか。

（やっぱ、URIつくって、ブランクノードにしないほうがいいかもですね。。。）

が、まずは、これでいいと思います。クローズします。

![高等学校学習指導要領-2018年3月-告示-学習指導要領LOD](https://user-images.githubusercontent.com/1328499/147399233-569dcf6e-bc88-43ea-bd9d-aefb8029af04.png)
