### ISSUE TITLE
教科の英語の出典ミス（特別の教科道徳など）

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#45]
https://w3id.org/jp-cos/UpperSecondaryDeptSNES-Intellectual/2019/特別の教科道徳

など、英語の出典がついていなかったので、修正

正規化処理の修正の一部見落としで、英語の出典がついていなかったので修正すること。

**Comment by yegusa** [comment]
修正しました。
cs-subjectArea-20211223.ttl

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
