### ISSUE TITLE
子がおかしいのがある　例：82n0000000000000

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#48]
小学校指導要領各教科（共通）の「第２章　各教科」
https://w3id.org/jp-cos/82n0000000000000

- OK「第1節 国語」　～　「第10節 外国語」の10個のみ　hasPart を持つ
- NG 上記以外のhasPartがある（「[第3学年]」とか「第2 各言語の目標及び内容等」など多数）

**Comment by yegusa** [comment]
#24 に関連

**Comment by masao** [comment]
修正した階層データを作りました:
* code2broader-20211226.txt

**Comment by masao** [comment]
ひとまず当該細目での修正パターンを反映しました

**Comment by yegusa** [comment]
いい感じだと思います。修正されたと思います。クローズします。
