### ISSUE TITLE
6桁目の誤り? 小学校・家庭

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#49]
- [x] 文科省に連絡
- [x] データの修正（備考つける）
- [x] 階層データ作成
- [x] 階層データttl作成
- [x] セクションラベルデータ作成
- [x] セクションラベルttl作成
- [x] リリース版に反映

#48 からの派生。

いくつかおかしな付番になっているものがある。
下記は家庭科のなかの一節だが、どれも6桁目で第5学年が付番されているが、前後の番号を見るとおそらく6桁目は D （第5・6学年）を付番すべきもののように思われる。

* https://w3id.org/jp-cos/82F0253110000000
* https://w3id.org/jp-cos/82F0253111000000
* https://w3id.org/jp-cos/82F0255110000000

**Comment by yegusa** [comment]
#43 の時と同じ作戦で、正しいコードと思われるほうになおして、備考に書くってやつで修正しちゃいましょう。

**Comment by yegusa** [comment]
文科省にも連絡しておきます。

**Comment by yegusa** [comment]
cs-items-20211226.ttl に反映させました。
よろ～。

**Comment by masao** [comment]
階層データも code2broader-20211226-3.txt として修正版をおきました

**Comment by yegusa** [comment]
code2broader-20211227.ttl 

修正しました

**Comment by masao** [comment]
セクションデータも更新して作り直しました。

**Comment by yegusa** [comment]
覚書： 2021-12-28 の修正では、このコード表（82V11）は修正されていないので、
次の82V12 が出たときに修正されるか確認すること。

**Comment by yegusa** [comment]
確認しました。クローズします。

https://w3id.org/jp-cos/82F02D3110000000
https://w3id.org/jp-cos/82F02D3111000000
https://w3id.org/jp-cos/82F02D5110000000
