### ISSUE TITLE
CourseOfStudyRevisionクラス記述が無い

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#5]
https://jp-cos.github.io/CourseOfStudyRevision

**Comment by yegusa** [comment]
作成しました。 cs-class-20211205.ttl

**Comment by masao** [comment]
![image](https://user-images.githubusercontent.com/38825/144753718-8d301fea-396e-4e86-b45c-633514f3d1d9.png)
追加されたのでクローズします。
