### ISSUE TITLE
84I1500000000000 の親は教科「情報」ではなく、第2款「各科目」

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#50]
#48 で直したのと同じようなところ。4桁目がゼロとなる細目を親に持ってくること。

https://w3id.org/jp-cos/84I1500000000000

誤
* 84I0000000000000 
  * 84I1500000000000 

正
* 84I0500000000000 
  * 84I1500000000000

**Comment by masao** [comment]
修正した親子関係ファイルを code2broader-20211226-2.txt としておきました。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
できていることを確認しました。クローズします。
