### ISSUE TITLE
sectionTextにHTML風の書式指定が入る

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#53]
元のExcelデータの中に入れられている書式指定が一部HTML風に変換される：

ex: https://w3id.org/jp-cos/7350233311000000

```turtle
cs:7350233311000000 cs:sectionText "関数<i>y</i>＝<i>ax</i><sup>2</sup>について，表，式，グラフを相互に関連付けて理解すること。".
```

修正するというよりは仕様として残しておいたほうが良いかも...

**Comment by yegusa** [comment]
以下のようにみえるんですね。

![jpcos-20211230-1](https://user-images.githubusercontent.com/1328499/147685597-e4497804-3794-4ee5-97e4-dd23b4ce7da7.png)

良いと思います。
仕様として、shapeファイルあたりの備考に書いておくといいかも？

たぶん、2021-12-28 文科省コードの更新のだけがそうなっているとおもわれるのだけど
（元ファイルのExcelへのコピペ方法を変えちゃったかも）
むしろ、他のもそうしたほうがいい？

**Comment by yegusa** [comment]
とりあえず、いったんクローズします。
