### ISSUE TITLE
aboutの段階リソースの出典プロパティの"の前に \がある

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#57]
どの問題に基因するのかは未調査（データのバグなのか、shapeファイルの書き方がまずいのか、about.htmlの作成方法の問題なのか？）

こんなかんじ。

![学習指導要領LODについて-about20220103](https://user-images.githubusercontent.com/1328499/147906335-5012c3d1-9eb5-4ce2-869f-b75e91f86607.png)

**Comment by masao** [comment]
元ファイルに不必要なエスケープが含まれていたので修正しました。

**Comment by yegusa** [comment]
修正されたことを確認しました。クローズします。
