### ISSUE TITLE
リソース説明の英語表記が無いものがある

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#58]
#46 からの派生。
英語版Aboutページにて必要な英語表記、以下のクラスの rdfs:comment は日本語しか存在しないので、追加が必要そう。

* cs:SourceOfEnglishName
* cs:Number

**Comment by yegusa** [comment]
ああ、空ノードだから、URIの説明がないからだねー。他のはURIの説明が最低限あるから。

他のリソースもついでに英語の説明を追加しておきますね。

**Comment by yegusa** [comment]
作っておきました

schema-class-20220104.ttl

**Comment by masao** [comment]
追加して反映しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
