### ISSUE TITLE
英語版 about にリソースのモデル概要図を追加

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#59]
日本語版は追加済み #35

- [x] 図の作成　@yegusa 
- [x] HTMLへ反映 @masao

**Comment by yegusa** [comment]
作りました。あと、よろしく～。 @masao 

![lod-model-en](https://user-images.githubusercontent.com/1328499/148139599-616fda8b-4138-4ba2-b69e-f2f7df01a1aa.png)

**Comment by masao** [comment]
反映しました。

**Comment by yegusa** [comment]
すまん、真ん中のリソースに日本語が・・・。英語に直しました。差し替えお願いします。
![lod-model-en](https://user-images.githubusercontent.com/1328499/152673182-403440e9-1cda-4c19-9432-a8b8f6e80f63.png)

**Comment by yegusa** [comment]
差し替えありがとー。確認しました。クローズします。
