### ISSUE TITLE
英語表記出典からのリンク先URIに誤り

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#6]
https://w3id.org/jp-cos/UpperSecondary/2018/地理歴史/歴史総合

からの英語表記出典の出典指導要領のURIとして https://w3id.org/jp-cos/UpperSecondarySchool/2018 だが、これは古いURI形式で、

正しくは https://w3id.org/jp-cos/UpperSecondary/2018 とすべき。

**Comment by yegusa** [comment]
Subject-*.ttl
SubjectArea-*.ttl 直しておきました。

**Comment by masao** [comment]
リンクが修正されたのを確認したのでクローズします。
![image](https://user-images.githubusercontent.com/38825/144753770-f1184c1b-17cc-4d2f-94c8-d354b10ccfe7.png)
