### ISSUE TITLE
各リソースの説明から対象クラスにリンクを加える

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#62]
現状、クラスのラベルが表示されており、対象となるクラスが明示されていないので、それを明記するようにするとよい。

現状：

> ## 学習指導要領の別バージョン
> 一部改正された学習指導要領を表すクラス。10年の間に一部改正が行われた場合などに利用。このリソースは次のようなURIにより表現されます。

修正後:

> ## 学習指導要領の別バージョン
> * 対象クラス: https://w3id.org/jp-cos/CourseOfStudyRevision
> 
> 一部改正された学習指導要領を表すクラス。10年の間に一部改正が行われた場合などに利用。このリソースは次のようなURIにより表現されます。

**Comment by masao** [comment]
リンクを追加しました

**Comment by yegusa** [comment]
確認しました。クローズします。
