### ISSUE TITLE
お知らせに発表を追加

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#65]
以下2件の最近の発表会の記事を About に足しておく：

- 学習指導要領LODの公開と活用の検討
  - 阿児雄之, 有山裕美子, 江草由佳, 榎本聡, 大井将生, 高久雅生
  - 2022年度アート・ドキュメンテーション学会年次大会, pp.17-17 (2022-06)
  - http://www.jads.org/news/2022/JADS2022061112.pdf

- 学習指導要領のLinked Open Data化による学習への利活用にむけた検討
  - 榎本聡, 大井将生, 高久雅生, 阿児雄之, 有山裕美子, 江草由佳
  - 日本教育工学会研究会, pp.135-142 (2022-05)
  - DOI https://doi.org/10.15077/jsetstudy.2022.1_135

**Comment by masao** [comment]
追加してみました。

**Comment by yegusa** [comment]
いい感じかと！クローズします。
