### ISSUE TITLE
aboutの英語の図に「子」がある

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#66]
「子」を英語に直した図に差し替えること

**Comment by yegusa** [comment]
作りました。 @masao 差し替えよろしく。

![lod-model](https://user-images.githubusercontent.com/1328499/185296720-53c3ed70-7de5-4757-bbe8-ad5e69678988.png)

**Comment by masao** [comment]
差し替えました

**Comment by yegusa** [comment]
確認しました。
