### ISSUE TITLE
セクション番号、セクションテキストが付加されていない細目がある

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#7]
https://jp-cos.github.io/74Q/e502000000000 にはセクション番号、セクションテキストが付加されていない。

**Comment by yegusa** [comment]
重複除去を失敗していたみたいです。

Fコードとの対応をとるための以下の記述だと、大文字小文字を区別していなかったもよう！

NG：（大文字小文字区別しない）
=INDEX(テーブル2[Fコード],MATCH([@コード],テーブル2[コード],0))

OK：大文字小文字を区別バージョン：
=INDEX(テーブル2[Fコード],MATCH(TRUE,EXACT([@コード],テーブル2[コード]),0))

これで、「Fコード」の値で重複除去しなおして作成し直ししました。

section-label-20211204.ttl です。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しましたのでクローズします。
