### ISSUE TITLE
82V12 コード表に更新（2022年3月14日更新）

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#72]
コード表一覧
https://www.mext.go.jp/a_menu/other/data_00002.htm

差分情報：82V11→82V12
https://www.mext.go.jp/content/20220311-mxt_syoto01-000010374_12.pdf

**Comment by masao** [comment]
当該箇所は既に現在公開のバージョンでは手で修正済み（こちらから修正指摘したデータ分）。

https://w3id.org/jp-cos/82F02D3110000000 ※注記付き

**Comment by yegusa** [comment]
#49 これの修正がでたってことですね。3つのコードが変わったみたいね。

https://w3id.org/jp-cos/82F02D3110000000
https://w3id.org/jp-cos/82F02D3111000000
https://w3id.org/jp-cos/82F02D5110000000

**Comment by yegusa** [comment]
もうすでに正しくしちゃってるので（注でわかる）ので、とりあえず、82V12はリリースしなくてもいいかも。
