### ISSUE TITLE
親子関係の取得ミス: 8Cn0000200000000 -> 8Hn0000240000000

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#75]
以下の関係が親子関係のようなので可能であれば取得すること：

* https://w3id.org/jp-cos/8Cn0000200000000
  * https://w3id.org/jp-cos/8Hn0000240000000

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。
