### ISSUE TITLE
存在しない教科へのリンク

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#78]
https://w3id.org/jp-cos/72n0000000000000 のリンク先が https://w3id.org/jp-cos/Elementary/2008/各教科(共通) となっているが、これは存在しない。単に教科リンクが不要なだけか？

**Comment by yegusa** [comment]
新しいコードの時に増えた教科？のよう。追加しておきました。もう一つ、中学校のもありました。

**Comment by yegusa** [comment]
subjectArea-*.ttlを更新。

**Comment by masao** [comment]
``qb:order`` が空になっているようです：

```turtle
<https://w3id.org/jp-cos/Elementary/2008/各教科(共通)> a <https://w3id.org/jp-cos/SubjectArea>; #教科リソース定義開始
  qb:order ; #表示順
  cs:school cs:school\/Elementary; #学校種別
```

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。
