### ISSUE TITLE
階層抽出の修正: 82G0233710000000

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#79]
階層関係の誤り:
* https://w3id.org/jp-cos/82G0233710000000 「(1) 健康な生活について，課題を見付け，その解決を目指した活動を通して，次の事項を身に付けることができるよう指導する。」の親が「体育」科目全体 https://w3id.org/jp-cos/82G0200000000000 になっているのは抽出ミス。

おそらく https://w3id.org/jp-cos/82G02C3700000000 「G 保健」の下位として設定すべき

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
OKと思います。
