### ISSUE TITLE
シェイプ記述誤り: Subjectリソースにおけるクラス指定

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#8]
https://w3id.org/jp-cos/SubjectShape における ``sourceRevisionOfCos`` プロパティのリンク先リソースのクラスを https://w3id.org/jp-cos/CourseOfStudyRevison を指定しているが、正しくは https://w3id.org/jp-cos/RevisionOfCourseOfStudy に変更になっている模様。

**Comment by yegusa** [comment]
#15 によって、データの方を https://w3id.org/jp-cos/CourseOfStudyRevison  に変更しました。よって、これは、シェイプの修正は、 プロパティsourceRevisionOfCos をプロパティcourseOfStudyRevison にするという変更に変えます。

**Comment by masao** [comment]
プロパティ修正を確認したのでクローズします。
