### ISSUE TITLE
LOD Cloudへの登録

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#83]
データセットを国際的に広報するためにLODクラウドに登録したい。
ただし残念ながら、2022年9月時点で登録申請フォームが落ちているようなので、オープンにならないかメンテナに聞いてみる必要あり...

参考: jp-textbook/jp-textbook.github.io#12

**Comment by masao** [comment]
久々に登録可能な状態になっていたので、以下を登録した：
 https://lod-cloud.net/dataset/jp-cos

外部リンク可能なリソースの情報をあとで追記すること。

**Comment by masao** [comment]
気づいたら、本家のLODクラウド2023-09-03版に追加されてました：
![lodcloud-jp-cos](https://github.com/jp-cos/jp-cos.github.io/assets/38825/3ff04c2f-5505-4988-a1b1-4c1d004d3867)

**Comment by masao** [comment]
![lod-cloud](https://github.com/user-attachments/assets/c4a2f572-d773-420b-af2c-008750968533)
LODクラウド2024-07-04付けも公開されてました。ノードの位置はたびたび変更になってますが。。。

**Comment by yegusa** [comment]
確認しました。クローズします。
