### ISSUE TITLE
表示文字列に言語指定情報を示す

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#84]
表示文字列に言語情報を追記して示す。
jp-textbook/jp-textbook.github.io#519 と同様の措置。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
こんな感じですね。

![image](https://github.com/jp-cos/jp-cos.github.io/assets/1328499/8ea784ee-f628-4406-aaf7-589d369c36b2)

確認しました。
