### ISSUE TITLE
学習指導要領解説データセットを取り込む

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#89]
https://ictconnect21.jp/cscode2023/
ICT Connect21 が公開した学習指導要領解説のデータセットを取り込む。

* Phase 1: PDF上のページ番号に飛ぶようにする。
* Phase 2: PDF内のテキストを抜き出しておいて、キーワード検索に資する形にする。

※上記データセットは2024年3月31日までの限定公開予定。

**Comment by masao** [comment]
指導要領コード | 枝番 | ページ数 | PDF URL
-- | -- | -- | --
8210000000000000 | 0 | 15 | https://www.mext.go.jp/content/20220606-mxt_kyoiku02-100002607_002.pdf
8210100000000000 | 0 | 15 | https://www.mext.go.jp/content/20220606-mxt_kyoiku02-100002607_002.pdf
8210100100000000 | 0 | 16 | https://www.mext.go.jp/content/20220606-mxt_kyoiku02-100002607_002.pdf

↓

```turtle
cs:8210000000000000 cs: commentaryPage <https://www.mext.go.jp/content/20220606-mxt_kyoiku02-100002607_002.pdf#page=15> .
```

**Comment by masao** [comment]
Phase3 : 解説内で示されているCSコード間の関係をうまくたどれるような形で整理すること。

cf. https://www.mext.go.jp/content/20220606-mxt_kyoiku02-100002607_002.pdf#page=46

![image](https://github.com/jp-cos/jp-cos.github.io/assets/38825/be980d6c-b23c-4d14-b5e3-35e449888daf)

**Comment by masao** [comment]
基本的なデータセット部分はそのまま追加しました。

**Comment by yegusa** [comment]
リンクを貼れていることを確認しましたのでクローズします。
