### ISSUE TITLE
シェイプ記述誤り: Subjectリソースにおける code03/fcode03 指定

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#9]
https://w3id.org/jp-cos/SubjectShape におけるシェイプ記述において ``cs:code03`` プロパティを指定しているが、実際のデータには code04 が記述されているので、シェイプ記述の誤りではないかと思われる。

**Comment by masao** [comment]
fcode03も同様。

**Comment by yegusa** [comment]
そうです！そのようになおしておきました。 code03 -> code04, fcode03->fcode04

**Comment by masao** [comment]
修正されたことを確認したのでクローズします。
