### ISSUE TITLE
学習指導要領コードを入力してそのコードのページへ行くフォーム

### ISSUE THREAD

**Issue by yegusa** [jp-cos/jp-cos.github.io#94]
ある学習指導要領コードのページをみたいとおもったときに、
自分でブラウザにURLを入れるのが結構面倒なので、

学習指導要領コードを入力するフォーム　表示ボタン

みたいな感じで、学習指導要領コードを入力して、表示ボタンをクリックすると
その学習指導要領のページに飛ぶようなフォームが
トップページにあるとよいのではないか？

以下のようなイメージ
![image](https://github.com/jp-cos/jp-cos.github.io/assets/1328499/a29c392f-036a-401d-ba2f-43c7831fbfd2)

**Comment by masao** [comment]
実装を追加しました。誤ったコードを入力した場合などのエラー処理も必要かもしれませんが、いまは not found に飛ぶだけです。

**Comment by yegusa** [comment]
確認しました。クローズします。
