### ISSUE TITLE
SUKILAM LODの活用／可視化ツールとの連携

### ISSUE THREAD

**Issue by masao** [jp-cos/jp-cos.github.io#96]
[SUKILAM LODの活用／可視化ツール](https://w3id.org/sukilam-educational-metadata/app/) 

おそらく NHK for School と同等の仕組みでつなげるはず…。

**Comment by masao** [comment]
https://gist.github.com/masao/6c4b238f21071330778fb7700ff1b534
簡単なテストコードを上記に置きました。あとはこれを本番ページに入れ込むだけ。

**Comment by masao** [comment]
一通り実装を追加しました。

**Comment by yegusa** [comment]
例：
https://w3id.org/jp-cos/8870202100000000

確認しました。クローズします。
